services:
  superalgos:
    container_name: superalgos
    build:
      context: ..
      dockerfile: ./docker/superalgos/Dockerfile
    image: ghcr.io/superalgos/superalgos:latest
    command: ["minMemo", "noBrowser"]
    user: "1001:1001"
    environment:
      - TZ=America/New_York
      - NODE_ENV=production
      - NODE_OPTIONS=--max_old_space_size=8192
      - PUID=1001
      - PGID=1001
      - PM2_HOME=/tmp/.pm2
    ports:
      - '34248:34248'
      - '18041:18041'
      - '18043:18043'
    volumes:
      - ./My-Data-Storage:/app/Platform/My-Data-Storage:z
      - ./My-Log-Files:/app/Platform/My-Log-Files:z
      - ./My-Workspaces:/app/Platform/My-Workspaces:z
      - ./My-Network-Nodes-Data:/app/Platform/My-Network-Nodes-Data:z
      - ./My-Social-Trading-Data:/app/Platform/My-Social-Trading-Data:z
      - superalgos-pm2-data:/tmp/.pm2
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 32768M
        reservations:
          memory: 16384M

  nginx:
    container_name: nginx
    image: nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      - TZ=America/New_York
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - api
      - worker
      - app
    networks:
      - frontend_network
      - backend_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

volumes:
  superalgos-pm2-data:
    driver: local